### ISSUE TITLE
[FEAT] Resizing columns to custom size

### ISSUE THREAD

**Issue by kareemmahlees** [kareemmahlees/tablex#96]
**Is your feature request related to a problem? Please describe.**
Sometimes the columns have long text data and it would be helpful to have the ability to resize the column to have more space.

**Describe the solution you'd like**
A resize handle should be displayed at the borders of the column that allows resizing.

**Additional context**
N/A

**Comment by christoff-linde** [comment]
hi @kareemmahlees, has this been looked at? otherwise keen to give this a go :)

**Comment by kareemmahlees** [comment]
Hey @christoff-linde sorry for the late response.

Yes, absolutely, I updated the description with some more useful info. Give it a try and don't hesitate to ask if you get stuck on something or need feedback 😊

**Comment by christoff-linde** [comment]
Hey @kareemmahlees, I was taking a look at starting the dev server locally, and I am for some reason getting a `panic` (see stacktrace below).

It appears that tauri (or more specifically sqlx) is failing to connect to/open a local sqlite db file. 

From how I understand the code (specifically `apps/desktop/src-tauri/src/state.rs:102:10`), it looks like a sqlite db file is expected in one of two places:
- `dev/data.db`
- `data.db`

Now I have tried creating these files manually locally (even though it appears as though it should be automatically created by `sqlx` on startup), but no success.

Perhaps I am doing something wrong, like not setting a config or environment variable somewhere? 

Just FYI, am running with:
- MacOS Version 26.0.1 (25A362)
- Xcode Command Line Tools: installed
- rustc: 1.88.0 (6b00bc388 2025-06-23)
- cargo: 1.88.0 (873a06493 2025-05-10)
- rustup: 1.28.2 (e4f3ad6f8 2025-04-28)
- Rust toolchain: 1.88-aarch64-apple-darwin
- node: 22.17.0
- npm: 10.9.2
- bun: 1.2.23

<details>

> when running `bun tauri dev`

```
warning: `tablex` (bin "tablex") generated 12 warnings (run `cargo fix --bin "tablex"` to apply 3 suggestions)
    Finished `dev` profile [unoptimized + debuginfo] target(s) in 1m 12s
     Running `/Users/christoff/source/repos/tools/tablex/target/debug/tablex`
2025-10-09 16:26:04 [TRACE] Triggered `applicationDidFinishLaunching`
2025-10-09 16:26:04 [TRACE] Creating new window
2025-10-09 16:26:04 [TRACE] Triggered `viewDidMoveToWindow`
2025-10-09 16:26:04 [TRACE] Completed `viewDidMoveToWindow`
2025-10-09 16:26:04 [TRACE] Triggered `validAttributesForMarkedText`
2025-10-09 16:26:04 [TRACE] Completed `validAttributesForMarkedText`
2025-10-09 16:26:04 [TRACE] Triggered `validAttributesForMarkedText`
2025-10-09 16:26:04 [TRACE] Completed `validAttributesForMarkedText`
2025-10-09 16:26:04 [TRACE] Triggered `validAttributesForMarkedText`
2025-10-09 16:26:04 [TRACE] Completed `validAttributesForMarkedText`
2025-10-09 16:26:04 [TRACE] Triggered `validAttributesForMarkedText`
2025-10-09 16:26:04 [TRACE] Completed `validAttributesForMarkedText`
2025-10-09 16:26:04 [TRACE] Triggered `validAttributesForMarkedText`
2025-10-09 16:26:04 [TRACE] Completed `validAttributesForMarkedText`
2025-10-09 16:26:04 [TRACE] Locked shared state in `set_fullscreen`
2025-10-09 16:26:04 [TRACE] Unlocked shared state in `set_fullscreen`
2025-10-09 16:26:05 [TRACE] Triggered `validAttributesForMarkedText`
2025-10-09 16:26:05 [TRACE] Completed `validAttributesForMarkedText`
2025-10-09 16:26:05 [TRACE] Triggered `validAttributesForMarkedText`
2025-10-09 16:26:05 [TRACE] Completed `validAttributesForMarkedText`
2025-10-09 16:26:05 [TRACE] Triggered `validAttributesForMarkedText`
2025-10-09 16:26:05 [TRACE] Completed `validAttributesForMarkedText`
2025-10-09 16:26:05 [TRACE] Triggered `validAttributesForMarkedText`
2025-10-09 16:26:05 [TRACE] Completed `validAttributesForMarkedText`
2025-10-09 16:26:05 [TRACE] Triggered `validAttributesForMarkedText`
2025-10-09 16:26:05 [TRACE] Completed `validAttributesForMarkedText`
2025-10-09 16:26:05 [TRACE] Triggered `viewDidMoveToWindow`
2025-10-09 16:26:05 [TRACE] Completed `viewDidMoveToWindow`

thread 'main' panicked at apps/desktop/src-tauri/src/state.rs:102:10:
Failed to establish connection: Database(SqliteError { code: 14, message: "unable to open database file" })
note: run with `RUST_BACKTRACE=1` environment variable to display a backtrace

thread 'main' panicked at library/core/src/panicking.rs:226:5:
panic in a function that cannot unwind
stack backtrace:
   0:        0x104a67794 - std::backtrace_rs::backtrace::libunwind::trace::h397b10519d455313
                               at /rustc/6b00bc3880198600130e1cf62b8f8a93494488cc/library/std/src/../../backtrace/src/backtrace/libunwind.rs:117:9
   1:        0x104a67794 - std::backtrace_rs::backtrace::trace_unsynchronized::h902ac8b376515985
                               at /rustc/6b00bc3880198600130e1cf62b8f8a93494488cc/library/std/src/../../backtrace/src/backtrace/mod.rs:66:14
   2:        0x104a67794 - std::sys::backtrace::_print_fmt::hd7805902c8299639
                               at /rustc/6b00bc3880198600130e1cf62b8f8a93494488cc/library/std/src/sys/backtrace.rs:66:9
   3:        0x104a67794 - <std::sys::backtrace::BacktraceLock::print::DisplayBacktrace as core::fmt::Display>::fmt::h2c3f7b4c4ce00f07
                               at /rustc/6b00bc3880198600130e1cf62b8f8a93494488cc/library/std/src/sys/backtrace.rs:39:26
   4:        0x104a8772c - core::fmt::rt::Argument::fmt::h1e6a80a47071126e
                               at /rustc/6b00bc3880198600130e1cf62b8f8a93494488cc/library/core/src/fmt/rt.rs:181:76
   5:        0x104a8772c - core::fmt::write::h1dbafa36e52e01c5
                               at /rustc/6b00bc3880198600130e1cf62b8f8a93494488cc/library/core/src/fmt/mod.rs:1446:25
   6:        0x104a63d04 - std::io::default_write_fmt::h09a684958e7b6931
                               at /rustc/6b00bc3880198600130e1cf62b8f8a93494488cc/library/std/src/io/mod.rs:639:11
   7:        0x104a63d04 - std::io::Write::write_fmt::he72d49f3084ee601
                               at /rustc/6b00bc3880198600130e1cf62b8f8a93494488cc/library/std/src/io/mod.rs:1914:13
   8:        0x104a67648 - std::sys::backtrace::BacktraceLock::print::h1fb87370474572ed
                               at /rustc/6b00bc3880198600130e1cf62b8f8a93494488cc/library/std/src/sys/backtrace.rs:42:9
   9:        0x104a69290 - std::panicking::default_hook::{{closure}}::h195a9b2c829547eb
                               at /rustc/6b00bc3880198600130e1cf62b8f8a93494488cc/library/std/src/panicking.rs:300:22
  10:        0x104a690e0 - std::panicking::default_hook::h18c3aa3e3a3584d5
                               at /rustc/6b00bc3880198600130e1cf62b8f8a93494488cc/library/std/src/panicking.rs:327:9
  11:        0x104a69d70 - std::panicking::rust_panic_with_hook::h02a9fa3cad928562
                               at /rustc/6b00bc3880198600130e1cf62b8f8a93494488cc/library/std/src/panicking.rs:833:13
  12:        0x104a69974 - std::panicking::begin_panic_handler::{{closure}}::hd1cc56578f819958
                               at /rustc/6b00bc3880198600130e1cf62b8f8a93494488cc/library/std/src/panicking.rs:699:13
  13:        0x104a67c58 - std::sys::backtrace::__rust_end_short_backtrace::h52c1e479035e4bc4
                               at /rustc/6b00bc3880198600130e1cf62b8f8a93494488cc/library/std/src/sys/backtrace.rs:168:18
  14:        0x104a69644 - __rustc[4794b31dd7191200]::rust_begin_unwind
                               at /rustc/6b00bc3880198600130e1cf62b8f8a93494488cc/library/std/src/panicking.rs:697:5
  15:        0x104ac8f54 - core::panicking::panic_nounwind_fmt::runtime::heb5dc4d12470415f
                               at /rustc/6b00bc3880198600130e1cf62b8f8a93494488cc/library/core/src/panicking.rs:117:22
  16:        0x104ac8f54 - core::panicking::panic_nounwind_fmt::h15b30cc5af643334
                               at /rustc/6b00bc3880198600130e1cf62b8f8a93494488cc/library/core/src/intrinsics/mod.rs:3196:9
  17:        0x104ac8fcc - core::panicking::panic_nounwind::hc7163b0cd384d969
                               at /rustc/6b00bc3880198600130e1cf62b8f8a93494488cc/library/core/src/panicking.rs:226:5
  18:        0x104ac9148 - core::panicking::panic_cannot_unwind::he04b9d4fe77d66ef
                               at /rustc/6b00bc3880198600130e1cf62b8f8a93494488cc/library/core/src/panicking.rs:331:5
  19:        0x1045af9e8 - tao::platform_impl::platform::app_delegate::did_finish_launching::he7ef2de3e4b34248
                               at /Users/christoff/.cargo/registry/src/index.crates.io-1949cf8c6b5b557f/tao-0.33.0/src/platform_impl/macos/app_delegate.rs:114:1
  20:        0x183492574 - <unknown>
  21:        0x1834fb0c4 - <unknown>
  22:        0x1834fb008 - <unknown>
  23:        0x18347108c - <unknown>
  24:        0x18567a3e0 - <unknown>
  25:        0x18788df1c - <unknown>
  26:        0x18788dccc - <unknown>
  27:        0x187df0db4 - <unknown>
  28:        0x187df45b8 - <unknown>
  29:        0x1855c82d4 - <unknown>
  30:        0x184c9a638 - <unknown>
thread caused non-unwinding panic. aborting.
```

</details>

**Comment by kareemmahlees** [comment]
Ayo @christoff-linde , I just pushed a fix here https://github.com/kareemmahlees/tablex/pull/139 that should resolve this
